# Generated by Django 4.2.5 on 2023-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('command', models.CharField(max_length=200)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
