# Generated by Django 4.2.5 on 2023-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0002_command_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='output',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(default='', max_length=200),
        ),
    ]
