# Generated by Django 4.2.5 on 2023-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0003_command_output_alter_command_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
