# Generated by Django 4.2.5 on 2023-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0004_alter_command_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
