# Generated by Django 4.2.5 on 2023-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0005_alter_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
