# Generated by Django 4.2.5 on 2023-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaipanApp', '0005_alter_command_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
